name: ci

on:
  push:
    branches:
      - act
  pull_request:
    branches:
      - act

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build
        run: bun run build
      
      - name: Package Keycloak plugin
        run: bunx keycloakify build

      - name: Archive jar files
        uses: actions/upload-artifact@v3
        with:
          name: theme
          path: dist_keycloak/*.jar